[alias]
lint = "clippy -- -W clippy::all -W clippy::pedantic -D warnings"
fmt = "fmt" 
check = "check"

[target."cfg(all())"]
# Keep builds deterministic and fast for dev
rustflags = ["-C", "debuginfo=2"]
